### ISSUE TITLE
TODO-LISTE

### ISSUE THREAD

**Issue by WoweePaw** [KaefGAMES/GiveMEaway-Tool#1]
## Meine TODO für kommende oder abgeschlossene Releases
# Support has ended
# Diese Software wird nicht länger supportet/entwickelt.

# 0.0.9
- [x] Kleinere Fixes
- [x] Wartezeit reduzieren beim Begrüßungsbildschirm
# 0.0.8, 0.0.8.1, 0.0.8.2 >
- [x] Updater wieder verfügbar machen (fix in 0.0.8.2)
- [x] BugFix "Settings-Menu" // Es ist wieder möglich die Soundeinstellungen vorzunehmen (fix in 0.0.8.2)
- [x] BugFix "Multiline-Key-Adding" // Es sollte jetzt möglich sein alle Keys hinzuzufügen. :)
- [x] Updater-Source hinzufügen (Nur für Devs interessant)
- [x] Sounds aktivier bzw. deaktivierbar machen
- [x] Sprachauswahl (Englisch & Deutsch)
- [x] Einstellungs-Fenster (Channel, Anbieter z.B. hitbox.tv usw.)
# 0.0.6 + 0.0.7
- [x] Updater fixen (sollte eigl. zu 0.0.4 schon laufen...dammit!)
- [x] Ausgewählten Key kopierbar machen
- [x] Random-Key auswählen für unentschlossene Gewinner ;)
- [x] Tooltips für alle Buttons
- [x] Durchnummerierung der Zeilen (Idee von nerdtopiaDE)
- [x] "Multiline-Key-Adding" also das hinzufügen mehrerer Keys mit einem Klick.
# 0.0.5
- [X] Komplette Liste löschbar machen
- [X] Keys löschbar machen
# 0.0.4
- [X] Keys hinzufügen und speichern (nicht länger temporär)
# 0.0.3 // Erster "Release"
- [X] Keys hinzufügen (temporär)
- [X] Keys anhand von keys.txt auslesen und anzeigen
- [X] Sound-Datei anpassbar machen für den Nutzer
- [X] "Useless-Button" zum Sound-Button umwandeln :3
# Pre-0.0.3 (0.0.2, 0.0.1, 0.0.0)
- [X] Useless-Button _^w^_
- [X] Template (Buttons, Textfelder usw.)
- [X] Codebasis
